### ISSUE TITLE
Clarify whether "first paint" or "first contentful paint" ever happens to a blank page

### ISSUE THREAD

**Issue by rniwa** [w3c/paint-timing#53] opened 2020-03-03 08:07 UTC
When the web page is truly blank, the current specification seems to indicate neither "First Paint" nor "First Contentful Paint " would never happen because the spec explicitly excludes "default background paint". Is that intentional?

**Comment by noamr** [comment] 2020-03-03 08:34
From my understanding of the spec, I think it is. For the vast majority of websites this would be a bug - they never actually paint.

**Comment by npm1** [comment] 2020-03-03 16:44
Yes, FP or FCP never trigger on a page with no content at all. If you think it's worthwhile, we can add a Note clarifying this.

**Comment by rniwa** [comment] 2020-03-04 05:58
I think it's worth adding a note clarifying this point. What happens if a content is later inserted after the page load had completed (e.g. page inserts content into an initially-blank iframe)? Do we still fire "first paint" or "first contentful paint" even 20min later?

**Comment by npm1** [comment] 2020-03-04 15:19
Ok, will add a note.

> What happens if a content is later inserted after the page load had completed (e.g. page inserts content into an initially-blank iframe)? Do we still fire "first paint" or "first contentful paint" even 20min later?

Yep, if a blank page inserts content on a very long setTimeout, the FP or FCP will be fired when that content is painted.

**Comment by rniwa** [comment] 2020-03-04 20:13
> If a blank page inserts content on a very long setTimeout, the FP or FCP will be fired when that content is painted.

I’m not sure that’s a desirable behavior. At that point, there is no correlation to the page load completing vs. FP/FCP. It might be better to cap at load event time.

**Comment by noamr** [comment] 2020-03-04 20:50
> > If a blank page inserts content on a very long setTimeout, the FP or FCP will be fired when that content is painted.
> 
> I’m not sure that’s a desirable behavior. At that point, there is no correlation to the page load completing vs. FP/FCP. It might be better to cap at load event time.

I tend to disagree - many of these client-rendered web apps load a blank page and then wait asynchronously while JS libs like React are loaded and until something is rendered... capping at load time would prevent them from seeing a lot of user-meaningful performance regressions.

What's the rationale of capping at load event time?

**Comment by rniwa** [comment] 2020-03-04 22:28
> > > If a blank page inserts content on a very long setTimeout, the FP or FCP will be fired when that content is painted.
> > 
> > 
> > I’m not sure that’s a desirable behavior. At that point, there is no correlation to the page load completing vs. FP/FCP. It might be better to cap at load event time.
> 
> I tend to disagree - many of these client-rendered web apps load a blank page and then wait asynchronously while JS libs like React are loaded and until something is rendered... capping at load time would prevent them from seeing a lot of user-meaningful performance regressions.

Well, we could wait for any async script as well. We don't necessarily tie to load event exactly.

> What's the rationale of capping at load event time?

So that FP/FCP track anything remotely related to the initial page load time. If a page stayed blank for 20min because that's the correct state of the page, and only later some script inserted content, I don't think it makes sense to call it the first contentful paint although it's probably rare for a website to do that so it may not matter in practice.

**Comment by noamr** [comment] 2020-03-05 07:05
> So that FP/FCP track anything remotely related to the initial page load time. If a page stayed blank for 20min because that's the correct state of the page, and only later some script inserted content, I don't think it makes sense to call it the first contentful paint although it's probably rare for a website to do that so it may not matter in practice.

Yea it's not a matter of practice, but could happen due to a bug, which FCP can help monitor in production.

**Comment by noamr** [comment] 2020-03-20 10:23
Can this be closed? @rniwa?

**Comment by rniwa** [comment] 2020-03-20 20:09
Did we add any clarification about this?

**Comment by noamr** [comment] 2020-03-22 07:28
How is this one? https://github.com/w3c/paint-timing/pull/72

**Comment by gi11es** [comment] 2020-03-23 12:34
For what it's worth, I think it's very useful to capture "outliers" that happen a long time after page load. They could be a telltale sign of a completely broken app. Without that signal of a very late paint timing, it might be difficult to catch that kind of bug.

**Comment by npm1** [comment] 2020-03-23 14:28
I think the spec is pretty clear: FP/FCP will fire when the conditions are met, if they are ever met. So I wouldn't think there's a need to clarify further. But not opposed to a non-normative note if others think it's useful.

**Comment by yoavweiss** [comment] 2020-03-24 14:35
Closing as #72 landed. Feel free to re-open if there's something else to discuss

**Closed by yoavweiss** 2020-03-24 14:35 UTC
