### ISSUE TITLE
Clarify whether First Contentful Paint considers content outside the viewport

### ISSUE THREAD

**Issue by smfr** [w3c/paint-timing#58] opened 2020-03-03 19:37 UTC
It's unclear now whether elements outside the viewport (generally, lower in the document than the visible portion) are counted for First Contentful Paint criteria.

Can a big video or SVG that's below the fold trigger FCP?

**Comment by npm1** [comment] 2020-03-03 20:57
In Chrome's implementation, we do paint a larger portion of DOM content than what fits within the viewport, and we do not currently do compute intersections with the viewport, so we allow paints outside of the viewport. I think we should allow user agent to consider content outside of the viewport to be FCP, for performance reasons and simplicity. What do you think?

**Comment by noamr** [comment] 2020-03-03 21:21
I believe that "when the browser renders pixels to the screen" has to mean "inside the viewport"; there is no screen outside the viewport and not so much point in counting pixels outside the viewport as painted.
This adds some complexity though because in some cases the FCP would be triggered by scrolling (a previously painted element being scrolled into view).

**Comment by smfr** [comment] 2020-03-03 21:23
Similarly, what is the affect of opacity:0 or transform: scale(0.001) on an element being considered for FCP? Do we care about actual pixels rendered, or the existence of boxes?

**Comment by noamr** [comment] 2020-03-03 21:37
The spirit of the spec is about pixel rendered, but at a coarse resolution... it's ok if it misses some edge cases as they're unlikely to be valid website use-cases - for example the case where the only content in the viewport is an element with scale(0.001) is unlikely... 

I would suggest that scale(0.001) is still considered rendered pixels and opacity: 0 isn't in terms of FCP, but I wonder how chrome handles it.

**Comment by anniesullie** [comment] 2020-03-03 21:56
I made a glitch to test some of the cases:

https://fcp-visibility-edge-cases.glitch.me/

* Out of viewport currently reports FCP on Chrome
* opacity: 0 currently does NOT report FCP on Chrome
* transform: scale(0.001) currently reports FCP on Chrome

I also took a look at Firefox's flag-gated `window.performance.timing.timeToNonBlankPaint` and it reports the timing in all 3 cases.

**Comment by smfr** [comment] 2020-03-03 22:12
It's probably also worth testing visibility:hidden and things clipped by overflow:hidden.

**Comment by anniesullie** [comment] 2020-03-03 22:34
Thanks, added these test cases. Both visibility:hidden and overflow:hidden do not report FCP on Chrome. All the test cases report timeToNonBlankPaint on Firefox.

**Comment by rniwa** [comment] 2020-03-03 22:38
> The spirit of the spec is about pixel rendered, but at a coarse resolution... it's ok if it misses some edge cases as they're unlikely to be valid website use-cases - for example the case where the only content in the viewport is an element with scale(0.001) is unlikely...

Missing some edge cases is okay but we still need a precise definition in the spec so that we can have multiple independent interoperable implementations.

**Comment by othermaciej** [comment] 2020-03-03 23:19
>  I think we should allow user agent to consider content outside of the viewport to be FCP, for performance reasons and simplicity. What do you think?

I think part of the question is not just whether it's allowed, but wether it's required. Do paints outside the viewport always count? Only some? Variable per-browser? Saying that this is totally browser-dependent is not good for interop, so that wouldn't be the best option.

**Comment by othermaciej** [comment] 2020-03-03 23:21
From notes above, it seems like Chrome is somewhat random about whether different forms of invisible paints count for FCP. The spec should be explicit about which are supposed to count to make it possible to achieve interop.

**Comment by noamr** [comment] 2020-03-04 14:09
I think we can make the spec very clear on one hand and allow optimizations/edge-cases on the other hand.

What matters for web developers who use this API here is the user experience - measuring when the users can actually consume/see content. 
Content outside the viewport, invisible text, content with opacity:0, scale(really-small-number), clipped content with overflow/clip-path, canvas that was only painted with the background image or transparent pixels: all are not really "contentful paints". 

I don't know how this works in spec-land, but my suggestion is that on one hand the spec would take the strict path regarding what's considered contentful-paint (if it's invisible or just a bg-color it's not contentful), and on the other hand leave room for browsers to optimize and find a fast semi-accurate path to achieve results that are "close enough" to the spirit of first-contentful-paint and would likely do the trick for 99% of websites and make implementations possible.

**Comment by othermaciej** [comment] 2020-03-04 17:24
I think we should assume that, eventually, web developers will come to depend on the edge cases of almost anything. So it's not really ok for a spec to require browsers to be "semi-accurate" or "close enough". If it does that, then it probably hasn't been specified enough to allow interop. I can see how it's convenient for the first implementation to not spell out the details, but it's dangerous for the second and subsequent implementations.

For the offscreen vs onscreen issue, we could say any of the following:
1. Painting outside the viewport always counts.
2. Painting outside the viewport counts as long as long as it's within X px of the edge of the viewport.
3. Painting outside the viewport never counts.
4. Painting outside the viewport MAY count.
5. Painting outside the viewport always counts, but browsers are allowed to not paint if they don't expect anything to paint within the viewport.

I think any of these options would be better than not addressing the issue at all.

I suspect that what Chrome has implemented is (5). It might be that what it has implemented is (2) though. I can't tell from the informal descriptions above. I think what we want in the spec is probably (5). And (5) is sort of equivalent to (1), since nothing in this spec requires browsers to paint at any specific time. (Though it's inconvenient if browsers don't paint close to the time when conditions for "first contentful paint are met.) So the "but" clause of (5) could even be a non-normative note. I think either (2) or (5) would be better for interop than (4).

**Comment by noamr** [comment] 2020-03-04 17:45
I like (2) better than (5) because it focuses on the user rather than the browser; Also the "viewport" should probably be "the viewport at load time", or to specify how this works with scrolling. 

btw none of this requires the browsers to paint, the whole spec is about when contentful paint is measured, not about when it's performed. Does the spec really need to include language about when browsers should/shouldn't paint? Isn't that a place where browsers can differentiate?

**Comment by npm1** [comment] 2020-03-04 18:06
(2) is more precise but too inflexible to work for all user agents precisely because they could use different strategies for preemptive painting outside of the viewport. We currently do (5), it seems good to me to add that to the spec.

**Comment by rniwa** [comment] 2020-03-05 20:45
Re-opening the issue since the PR didn't make it clear which viewport is being used.

**Comment by npm1** [comment] 2020-03-06 17:08
Sure, I can add a link. It doesn't matter which one is used because what the text means is that all paints count (whether inside or outside the viewport).

**Comment by rniwa** [comment] 2020-03-06 20:21
Ugh... no, I wasn’t talking about the linking. Is it the initial viewport or the actual viewport. The term “viewport” is ambiguous on its own when talking about whether something is in it or not.

**Comment by rniwa** [comment] 2020-03-06 20:21
Can we stop keep landing PRs and closing this issue without fully understanding what the issue is?

**Comment by rniwa** [comment] 2020-03-06 20:23
The spec also doesn’t define what it means for something to be inside or outside whichever viewport we’re talking about. That too requires a formal definition. For starters, what geometry of what content are we talking about? The bounding box? All these things need to be sorted out before we can land a PR & close this issue.

**Comment by yoavweiss** [comment] 2020-03-06 21:34
Apologies. I think I now have a better understanding of your concerns.

At the same time, it seems like that the [FP](https://w3c.github.io/paint-timing/#first-paint) and [FCP](https://w3c.github.io/paint-timing/#first-contentful-paint) definitions cover "any rendering (that fits the FP/FCP criteria) regardless of viewport location, in whatever viewport". So it seems to me we could avoid mentioning any kind of viewport in the normative text, and just add the viewport mention as a non-normative clarification.

Would that work?

**Comment by rniwa** [comment] 2020-03-06 22:12
That might work if the definition of something getting painted does not depend on viewport at all; e.g. involves all or any CSS box generated for the document and doesn’t care its location.

We might need to be mindful of websites that put content outside the viewport for accessibility purposes though... not sure if it’s common to have those contents before anything painted, or if that’s common enough to warrant a special treatment.

**Comment by smfr** [comment] 2020-03-06 22:24
Consider `<div style='position:absolute; left: -1000px>Some text here</div>`

**Comment by othermaciej** [comment] 2020-03-07 05:22
It seems like the intent is that _if_ such contents get painted, they are eligible to count as a First Paint and First Contentful Paint, but there is no requirement for the browser to paint merely because such content is present in the layout.

Unfortunately, the HTML [update the rendering steps](https://html.spec.whatwg.org/#event-loop-processing-model) require the browser to mark paint timing even if it believes there would be no visible effects and thus chooses not to paint:

> 3. Unnecessary rendering: If there are browsing contexts browsingContexts for which the user agent believes updating the rendering would have no visible effect and which possess no Document objects with a non-empty map of animation frame callbacks, then remove from docs all Document objects whose browsing context is in browsingContexts. Invoke the mark paint timing algorithm for each Document object removed.

Thus, it's not possible for Paint Timing to allow this, because even if the browser chooses not to paint, it must mark paint timing. And "mark paint timing" always happens before the actual paint, so it can't have information from what was painted to bail out early.

Thus, it's not actually possible to implement the desired rule in Paint Timing without either changing HTML, or changing the definition of what counts as a First Paint or a First Contentful Paint.

**Comment by noamr** [comment] 2020-03-08 21:09
> Consider `<div style='position:absolute; left: -1000px'>Some text here</div>`
See PR: https://github.com/w3c/paint-timing/pull/66
Also covers cases of scale(0.001). The idea is that the threshold for an element to become "paintable" is to be intersecting with the document. In both these cases the element would not intersect with the document.

**Comment by npm1** [comment] 2020-03-09 14:24
> Ugh... no, I wasn’t talking about the linking. Is it the initial viewport or the actual viewport. The term “viewport” is ambiguous on its own when talking about whether something is in it or not.

`Initial viewport` and `actual viewport` are confusing, and there is an open [issue](https://github.com/w3c/csswg-drafts/issues/206) to rename them. What I'd link here is 'visual viewport' but I didn't see it defined anywhere. As Yoav and I have noted, 'any paint counts' is the answer to the 'underlying issue'.

> Consider `<div style='position:absolute; left: -1000px'>Some text here</div>`

I don't follow why that is an interesting case. Is that inside a viewport, under any definition of viewport?

> I think the best solution would be to remove the invocation of "mark paint timing" from Step 3 of HTML's "update the rendering" steps. It's not clear to me why it is there, because a paint that doesn't happen cannot reasonably be considered a First Paint or First Contentful Paint.

It's there for security reasons. If an attacker adds a single visited styled link whose visibility depends on whether the user has visited the site, then paint timing must report paint values in both cases. I can see how that section is confusing though. Perhaps it would be better to note that under certain conditions the user agent must paint that document, even if the paint operation is not going to produce any changes.

**Comment by noamr** [comment] 2020-03-09 15:36
> It's there for security reasons. If an attacker adds a single visited styled link whose visibility depends on whether the user has visited the site, then paint timing must report paint values in both cases. I can see how that section is confusing though. Perhaps it would be better to note that under certain conditions the user agent must paint that document, even if the paint operation is not going to produce any changes.
How can visibility depend on visited link status? :visited pseudo-element doesn't allow that.

**Comment by noamr** [comment] 2020-03-09 15:36
> It's there for security reasons. If an attacker adds a single visited styled link whose visibility depends on whether the user has visited the site, then paint timing must report paint values in both cases. I can see how that section is confusing though. Perhaps it would be better to note that under certain conditions the user agent must paint that document, even if the paint operation is not going to produce any changes.


How can visibility depend on visited link status? :visited pseudo-element doesn't allow that.

**Comment by smfr** [comment] 2020-03-09 15:54
> > Ugh... no, I wasn’t talking about the linking. Is it the initial viewport or the actual viewport. The term “viewport” is ambiguous on its own when talking about whether something is in it or not.
> 
> `Initial viewport` and `actual viewport` are confusing, and there is an open [issue](https://github.com/w3c/csswg-drafts/issues/206) to rename them. What I'd link here is 'visual viewport' but I didn't see it defined anywhere.

The as-yet-unpublished css-viewport spec will define it. Still working on the first ED.

**Comment by npm1** [comment] 2020-03-09 18:00
> How can visibility depend on visited link status? :visited pseudo-element doesn't allow that.

If you have a webpage with a single link with a visited style of `color: white` then the page will look completely white when the link has been visited. Maybe this should be solved from the CSS spec defining that styling?

**Comment by noamr** [comment] 2020-03-09 18:08
> > How can visibility depend on visited link status? :visited pseudo-element doesn't allow that.
> 
> If you have a webpage with a single link with a visited style of `color: white` then the page will look completely white when the link has been visited. Maybe this should be solved from the CSS spec defining that styling?

It will still be considered paintable and contentful from the point of view of FCP.

**Comment by npm1** [comment] 2020-03-09 19:36
Ok, then we can remove the `mark the paint timing` for documents for which rendering is not necessary.

**Comment by rniwa** [comment] 2020-03-09 23:49
> > Ugh... no, I wasn’t talking about the linking. Is it the initial viewport or the actual viewport. The term “viewport” is ambiguous on its own when talking about whether something is in it or not.
> 
> `Initial viewport` and `actual viewport` are confusing, and there is an open [issue](https://github.com/w3c/csswg-drafts/issues/206) to rename them. What I'd link here is 'visual viewport' but I didn't see it defined anywhere. As Yoav and I have noted, 'any paint counts' is the answer to the 'underlying issue'.

Sounds like we're being blocked by the css-viewport spec then.

> > Consider `<div style='position:absolute; left: -1000px'>Some text here</div>`
> 
> I don't follow why that is an interesting case. Is that inside a viewport, under any definition of viewport?

It's interesting because it's outside the layout or visual viewport, and it would never come into either viewport. This is a common technique used to have text for accessibility purposes but not to render it to the user. e.g. used to basically add alt text for a background image. I don't think we want to consider this text as a part of the FCP if at all possible.

**Comment by noamr** [comment] 2020-03-10 11:10
> > > Ugh... no, I wasn’t talking about the linking. Is it the initial viewport or the actual viewport. The term “viewport” is ambiguous on its own when talking about whether something is in it or not.
> > 
> > 
> > `Initial viewport` and `actual viewport` are confusing, and there is an open [issue](https://github.com/w3c/csswg-drafts/issues/206) to rename them. What I'd link here is 'visual viewport' but I didn't see it defined anywhere. As Yoav and I have noted, 'any paint counts' is the answer to the 'underlying issue'.
> 
> Sounds like we're being blocked by the css-viewport spec then.
> 
> > > Consider `<div style='position:absolute; left: -1000px'>Some text here</div>`
> > 
> > 
> > I don't follow why that is an interesting case. Is that inside a viewport, under any definition of viewport?
> 
> It's interesting because it's outside the layout or visual viewport, and it would never come into either viewport. This is a common technique used to have text for accessibility purposes but not to render it to the user. e.g. used to basically add alt text for a background image. I don't think we want to consider this text as a part of the FCP if at all possible.

I agree, added it to my PR.

**Comment by noamr** [comment] 2020-03-10 14:31
> > > Ugh... no, I wasn’t talking about the linking. Is it the initial viewport or the actual viewport. The term “viewport” is ambiguous on its own when talking about whether something is in it or not.
> > 
> > 
> > `Initial viewport` and `actual viewport` are confusing, and there is an open [issue](https://github.com/w3c/csswg-drafts/issues/206) to rename them. What I'd link here is 'visual viewport' but I didn't see it defined anywhere. As Yoav and I have noted, 'any paint counts' is the answer to the 'underlying issue'.
> 
> Sounds like we're being blocked by the css-viewport spec then.
I believe that paint-timing spec should not have anything to do with viewports (based on previous discussion here). when "Mark Paint Timing" is called (it's an event loop consideration if/when to call it), "first-contentful-paint" entry should be added if there are paintable & contentful elements in the document. I do agree that the rendering-loop spec needs to be clearer about visual vs. initial viewport.

**Comment by noamr** [comment] 2020-03-23 17:13
> We have a [fcp-invisible-text](https://github.com/web-platform-tests/wpt/blob/master/paint-timing/fcp-only/fcp-invisible-text.html#L10) which expects FCP for invisible text (`rgba(0, 0, 0, 0)`). Based on the above discussion, I'd assume that FCP shouldn't be reported here?

FCP should be reported for that text. Text color does not affect contentfulness.

**Comment by mstange** [comment] 2020-03-23 17:24
> (2) is more precise but too inflexible to work for all user agents precisely because they could use different strategies

Interoperability is more important than flexibility for user agents.
In Firefox, invisible text is not added to the display list during paint, so the particular case that's exercised by the `fcp-invisible-text` test already impacts "flexibility" for user agent implementation.

**Comment by noamr** [comment] 2020-03-23 18:39
> > (2) is more precise but too inflexible to work for all user agents precisely because they could use different strategies
> 
> Interoperability is more important than flexibility for user agents.
> In Firefox, invisible text is not added to the display list during paint, so the particular case that's exercised by the `fcp-invisible-text` test already impacts "flexibility" for user agent implementation.

I think it would be better to remain interoperable where possible... I think it's reasonable to make fully-transparent text (rgba/hsla with a==0) non-contentful. It shouldn't have a visited-link privacy issue since RGBA/HSLA is not allowed for `:visited`. @rniwa, @npm1 ?

**Comment by npm1** [comment] 2020-03-23 19:04
Just to clarify, `visibility: hidden` makes the text not eligible for FCP at first, and then changing it to `visible` triggers FCP. Does Firefox not paint text that is marked visible but with the same color as the background? For example, if I change the background to blue (or any non-white) and then add text of that same color, is that text not painted?

**Comment by npm1** [comment] 2020-03-23 19:05
In general I don't think we want to get into the problem of detecting actual visibility of text. I could add a background image that is of some color and then add text of that same color. There seem to be many ways of achieving this kind of 'invisible text'.

**Comment by mstange** [comment] 2020-03-23 19:15
> Does Firefox not paint text that is marked visible but with the same color as the background?

Oh, no, detecting that would be way too complicated. Firefox only has [a simple "is text transparent" check](https://searchfox.org/mozilla-central/rev/202a285024f174c2d2bf2152d9cba90a03723eab/layout/generic/nsTextFrame.cpp#4850-4862).

**Comment by noamr** [comment] 2020-03-23 19:21
I think that in WebKit implementing this wouldn't be difficult; It would also need to account for `text-shadow` like you do in nsTextFrame. We don't need to go as far as background detection (also that would start having a `:visited` link implication).

**Comment by npm1** [comment] 2020-03-23 19:45
Ah I see. That seem reasonable to me too (we'll need to change Chromium implementation though).

**Comment by noamr** [comment] 2020-03-24 16:07
Since this issue is about viewport, I created a new one (https://github.com/w3c/paint-timing/issues/75) specifically for transparent text (text with alpha=0)

**Comment by noamr** [comment] 2020-03-31 09:22
I believe this can be closed now?

**Comment by rniwa** [comment] 2020-04-01 22:54
Yup.

**Closed by rniwa** 2020-04-01 22:54 UTC
Labels: requires-discussion
